all:
	gcc -o canopen ch22-01.c
	gcc -o upper ch22-02.c
	gcc -o fcat ch22-03.c
	gcc -o letter-count ch22-04a.c
	gcc -o word-count ch22-04b.c
	gcc -o line-count ch22-04c.c
	gcc -o xor ch22-05.c
	gcc -o hex-view ch22-06.c
	gcc -o compress_file ch22-07a.c
	gcc -o uncompress_file ch22-07b.c
	gcc -o inventory-merge ch22-09.c
	gcc -o pdate ch22-11.c
	gcc -o pproduct ch22-12.c
	gcc -o flight ch22-13.c
	gcc -o enc ch22-14.c
	gcc -o fcopy ch22-16.c
	gcc -o pphone ch22-17.c
	gcc -o mmm ch22-18.c
	gcc -o w2u ch22-19a.c
	gcc -o u2w ch22-19b.c

clean:
	rm -f canopen upper fcat letter-count word-count line-count xor
	rm -f hex-view compress_file uncompress_file inventory-merge pdate pproduct flight
	rm -f enc fcopy pphone mmm w2u u2w