all:
	gcc -o canopen ch22-01.c
	gcc -o upper ch22-02.c
	gcc -o fcat ch22-03.c
	gcc -o letter-count ch22-04a.c
	gcc -o word-count ch22-04b.c
	gcc -o line-count ch22-04c.c
	gcc -o xor ch22-05.c
	gcc -o hex-view ch22-06.c
	gcc -o compress_file ch22-07a.c
	gcc -o uncompress_file ch22-07b.c

clean:
	rm -f canopen upper fcat letter-count word-count line-count xor
	rm -f hex-view compress_file uncompress_file